### ISSUE TITLE
Are SFC translations scoped to the current component?

### ISSUE THREAD

**Issue by wreality** [fluent-vue/examples#11]
Just started messing around with fluent-vue, so apologies if I'm missing the answer to this in the docs.

Are the translations in an SFC scoped to just that component?

I'm trying to add translations to a parent component that the child component will use.  In some cases its for organization, in others because the child components are generic

**Comment by Demivan** [comment]
Yes, translations defined in SFC are scoped to just that component. Translations added directly to the bundle are global and available for every component in the app.

In early versions of the library there was functionality that allowed sharing parent translations with the child component. But this causes a lot of copying messages between bundles causing slowdown (`fluent.js` itself does not have a concept of parent translations)

Few times that I needed this I either moved translations to an external ftl file and added its content later to a bundle, or passed translation from a parent component as prop.

What is your use-case? Can you send an example?
